language: ruby
rvm:
- 2.1.0
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  - "psql -c 'create database pindd_test;' -U postgres"
  - "rake db:migrate"
env:
  SECRET_KEY_BASE="$(bundle exec rake secret)"
