language: ruby
rvm:
- 2.1.0
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  - "psql -c 'create database pindd_test;' -U postgres"
  - "rake db:migrate"
env:
  global:
  secure: "hxlP6pA9SGfIh+6MpF4ChYBIYH1Sc/n7JXoO2vTYFmbP1l7KGOh5Fys7l3xyXD57rzAUSVZOs2wovozhZYw3UqIRIp6QSCzh80QD33cMyTF8FrWJyTqzHJdd/TTQzKkJT7lrLMnvCQknk2zkdlqCwXJaC/V/eMH1x2EgvAgTlYg="
