# Faye
development:
  server: "http://localhost:9292/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js" 
  auth_token: dfgdfgr4554trtgref3454
  adapter: "Faye"
  async: true

# Pusher
# development:
#   adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js" 
#   app_id: "YOUR_PUSHER_APP_ID"
#   api_key: "YOUR_PUSHER_API_KEY"
#   auth_token: "YOUR_PUSHER_SECRET"
#   adapter: "Pusher"
#   async: true

test:
  server: "http://localhost:9292/faye"
  adapter_javascript_url: "http://localhost:9292/faye/faye.js" 
  adapter: "Faye"
  auth_token: "secret"
  async: false

production:
   adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js" 
   app_id: <%= ENV["PUSHER_APP_ID"] %>
   api_key: <%= ENV["PUSHER_KEY"] %>
   auth_token: <%= ENV["PUSHER_SECRET"] %>
   adapter: "Pusher"
   async: true